# basic options
title: Guide Learning
author: Luxfi 20
email: kazehayakirito20@gmail.com
description: Welcome To Website
twitter_username: luxfi9
github_username:  luxfi20

# Build settings
markdown: kramdown
theme: manima
